Tracker/Controllers/API/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Tracker.Models;

namespace Tracker.Controllers.API
{
    public class ResumeController : ApiController
    {
        // GET: api/Resume
        [HttpGet]
        [Route("resumes")]
        public HttpResponseMessage GetResumes(HttpRequestMessage request)
        {
            var resumes = DataFactory.GetResumes();
            return request.CreateResponse<Resume[]>(HttpStatusCode.OK, resumes.ToArray());
        }

        // GET: api/Resume/5
        [HttpGet]
        [Route("resume/{resumeId}")]
        public HttpResponseMessage GetResume(HttpRequestMessage request, int resumeId)
        {
            var resumes = DataFactory.GetResumes();
            var resume = resumes.FirstOrDefault(item => item.ResumeId == resumeId);
            return request.CreateResponse<Resume>(HttpStatusCode.OK, resume);
        }

        [HttpGet]
        [Route("skills")]
        public HttpResponseMessage GetProducts(HttpRequestMessage request)
        {
            var products = DataFactory.GetSkillset();

            return request.CreateResponse<Skillset[]>(HttpStatusCode.OK, products.ToArray());
        }

        [HttpGet]
        [Route("skills/{skillsetId}")]
        public HttpResponseMessage GetProduct(HttpRequestMessage request, int productId)
        {
            var products = DataFactory.GetSkillset();
            var product = products.FirstOrDefault(item => item.SkillsetId == productId);

            return request.CreateResponse<Skillset>(HttpStatusCode.OK, product);
        }

        [HttpGet]
        [Route("skills")]
        public HttpResponseMessage GetSkills(HttpRequestMessage request)
        {
            var orders = DataFactory.GetSkillset();

            return request.CreateResponse<Skillset[]>(HttpStatusCode.OK, orders.ToArray());
        }

    }
}

Tracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET MVC with Angular JS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body data-ng-app="main" class="responsive">
    <div id="banner" class="navbar-fixed-top">
        <div class="container">
            <div class="row banner">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="ui-corner-all col-sm-3, col-md-3, col-lg-3">
                        <img src="~/Images/TwitterAvatar.jpg" alt="avatar" />
                    </div>
                    <div class="navbar-collapse collapse col-sm-3, col-md-3, col-lg-3">
                        <ul class="portfolioNavigation">
                            <li>
                                @Html.ActionLink("Justine's Portfolio",
                                "Index",
                                "Home")
                            </li>
                            <li>
                                @Html.ActionLink("Resumes",
                                "Resume",
                                "Home")
                            </li>
                            <li>
                                @Html.ActionLink("Skills",
                                "Skills",
                                "Home")
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Justine Alires Portfolio</p>
    </footer>
</div>

@Scripts.Render("~/bundles/angular")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script type="text/javascript">
            window.MyApp = {};
            MyApp.rootPath = '@Url.Content("~")';
</script>
<script src="~/App/Validator.js"></script>
<script src="~/App/App.js"></script>
@RenderSection("scripts", required: false)
<script type="text/javascript">
            @RenderSection("jsCode", required: false)
</script>
</body>
</html>